cluster:
  name: "raft-cluster"       # Название кластера
  nodes:                     # Список всех узлов
    - id: "node-1"           # Уникальный ID узла
      address: "10.0.0.1:8080"
      role: "voter"          # Роль: voter/non-voter
    - id: "node-2"
      address: "10.0.0.2:8080"
      role: "voter"
    - id: "node-3"
      address: "10.0.0.3:8080"
      role: "voter"

raft:
  data_dir: "/var/lib/raft"  # Общие настройки Raft
  snapshot_interval: 1024
